CREATE DATABASE IF NOT EXISTS `impactoacademico`;
USE `impactoacademico`;

DROP TABLE IF EXISTS `Alumnos`;
CREATE TABLE IF NOT EXISTS `Alumnos` (
  `id` int NOT NULL,
  `Cuenta` int NOT NULL,
  `Nombre` varchar(50) NOT NULL,
  `password` varchar(200) NOT NULL,
  `id_Carrera` varchar(3) NOT NULL,
  PRIMARY KEY (`Cuenta`),
  KEY `id_Carrera` (`id_Carrera`)
);

DROP TABLE IF EXISTS `Carrera`;
CREATE TABLE IF NOT EXISTS `Carrera` (
  `id_Carrera` varchar(3) NOT NULL,
  `nm_Carrera` varchar(50) NOT NULL,
  PRIMARY KEY (`id_Carrera`)
);

INSERT INTO `Carrera` VALUES
('ISI', 'Ingeniería en Sistemas Inteligentes'),
('ITR', 'Ingeniería en Transporte'),
('LCI', 'Licenciatura en Comercio Internacional'),
('LES', 'Licenciatura en Educación para la Salud'),
('LSD', 'Licenciatura en Seguridad Ciudana');

DROP TABLE IF EXISTS `Materias`;
CREATE TABLE IF NOT EXISTS `Materias` (
  `id_Materia` int NOT NULL,
  `id_Carrera` varchar(3) NOT NULL,
  `Semestre` int NOT NULL,
  `Nombre` varchar(200)NOT NULL,
  PRIMARY KEY (`id_Materia`),
  KEY `id_Carrera` (`id_Carrera`)
);

INSERT INTO `Materias` VALUES
(10, 'ISI', 1, 'Psicologia'),
(11, 'ISI', 1, 'Algebra Superior'),
(12, 'ISI', 1, 'Calculo I'),
(13, 'ISI', 1, 'Matematicas Discretas'),
(14, 'ISI', 1, 'Geometria Analitica'),
(15, 'ISI', 1, 'Fundamentos de Programacion'),
(16, 'ISI', 10, 'Taller de Tesis'),
(17, 'ISI', 10, 'Robotica'),
(18, 'ISI', 10, 'Logica Difusa'),
(19, 'ISI', 10, 'Practica Profesional'),
(20, 'ISI', 10, 'Taller con Weka'),
(21, 'ISI', 10, 'Taller de Mineria de Datos'),
(22, 'ISI', 10, 'Redes Neuronales Modulares'),
(23, 'ISI', 10, 'Razonamiento Basado en Casos'),
(24, 'ISI', 10, 'Graficacion'),
(25, 'ISI', 10, 'Programacion con Matlab'),
(26, 'ISI', 10, 'Agentes Inteligentes'),
(27, 'ISI', 10, 'Maquinas de Soporte Vectorial'),
(28, 'ISI', 2, 'Ingles C1'),
(29, 'ISI', 2, 'Algebra Lineal'),
(30, 'ISI', 2, 'Calculo II'),
(31, 'ISI', 2, 'Ecuaciones Diferenciales'),
(32, 'ISI', 2, 'Lenguajes y Automatas'),
(33, 'ISI', 2, 'Programacion Orientada a Objetos'),
(34, 'ISI', 3, 'Ingles C2'),
(35, 'ISI', 3, 'Calculo III'),
(36, 'ISI', 3, 'Probabilidad y Estadistica'),
(37, 'ISI', 3, 'Fisica Basica'),
(38, 'ISI', 3, 'Estructura de Datos'),
(39, 'ISI', 3, 'Logica Matematica'),
(40, 'ISI', 4, 'Electricidad y Magnetismo'),
(41, 'ISI', 4, 'Quimica'),
(42, 'ISI', 4, 'Metrologia'),
(43, 'ISI', 4, 'Organizacion de Archivos'),
(44, 'ISI', 4, 'Introduccion a la Inteligencia Artificial'),
(45, 'ISI', 4, 'Psicologia Avanzada'),
(46, 'ISI', 5, 'Circuitos Electricos'),
(47, 'ISI', 5, 'Metodos Numericos'),
(48, 'ISI', 5, 'Lenguaje Ensamblador'),
(49, 'ISI', 5, 'Programacion Web'),
(50, 'ISI', 5, 'Fundamentos de Bases de Datos'),
(51, 'ISI', 5, 'Introduccion al Tratamiento de Imagenes'),
(52, 'ISI', 6, 'Arquitectura de Computadoras'),
(53, 'ISI', 6, 'Compiladores'),
(54, 'ISI', 6, 'Sistemas Basados en Conocimiento'),
(55, 'ISI', 6, 'Bases de Datos Distribuidas'),
(56, 'ISI', 6, 'Introduccion al Reconocimiento de Patrones'),
(57, 'ISI', 6, 'Preparacion de Datos'),
(58, 'ISI', 7, 'Redes de Computadoras I'),
(59, 'ISI', 7, 'Sistemas Operativos'),
(60, 'ISI', 7, 'Ingenieria del Software'),
(61, 'ISI', 7, 'Arboles de Desicion'),
(62, 'ISI', 7, 'Mineria de Datos I'),
(63, 'ISI', 7, 'Data Warehouse I'),
(64, 'ISI', 7, 'Evaluacion e Interpretacion del Conocimiento'),
(65, 'ISI', 8, 'Redes de Computadoras II'),
(66, 'ISI', 8, 'Sistemas Operativos Distribuidos'),
(67, 'ISI', 8, 'Mineria de Datos II'),
(68, 'ISI', 8, 'Visualizacion de Datos'),
(69, 'ISI', 8, 'Redes Neuronales Supervisadas'),
(70, 'ISI', 8, 'Data Warehouse II'),
(71, 'ISI', 8, 'Interpretacion de Imagenes'),
(72, 'ISI', 9, 'Algoritmos de Clasificacion'),
(73, 'ISI', 9, 'Algoritmos de Agrupamiento'),
(74, 'ISI', 9, 'Procesamiento de Lenguaje Natural'),
(75, 'ISI', 9, 'Reconocimiento de Patrones Sintactico-Estructural'),
(76, 'ISI', 9, 'Redes Neuronales no Supervisadas'),
(77, 'ISI', 9, 'Algoritmos Geneticos'),
(78, 'ITR', 1, 'Algebra Superior'),
(79, 'ITR', 1, 'Expresion Grafica Automatizada'),
(80, 'ITR', 1, 'Fisica General'),
(81, 'ITR', 1, 'Taller de expresion escrita'),
(82, 'ITR', 1, 'Electricidad y magnetismo'),
(83, 'ITR', 1, 'Lenguaje de programacion'),
(84, 'ITR', 10, 'Practicas profesionales'),
(85, 'ITR', 10, 'Programacion de corridas ferroviarias'),
(86, 'ITR', 10, 'Administracion de empresas ferroviarias'),
(87, 'ITR', 10, 'Politicas de autotransporte ferroviario'),
(88, 'ITR', 10, 'Modelos de impacto ambiental del autotransporte ferroviario'),
(89, 'ITR', 10, 'Taller intermodal del autotransporte ferroviario'),
(90, 'ITR', 10, 'Sistemas inteligentes del autotransporte ferroviario'),
(91, 'ITR', 10, 'Control de trafico aereo'),
(92, 'ITR', 10, 'Administracion de empresas aereas'),
(93, 'ITR', 10, 'Politicas de autotransporte aereo'),
(94, 'ITR', 10, 'Modelos de impacto ambiental del autotransporte aereo'),
(95, 'ITR', 10, 'Taller intermodal del autotransporte aereo'),
(96, 'ITR', 10, 'Sistemas inteligentes del autotransporte aereo'),
(97, 'ITR', 10, 'Programacion de corridas maritimas'),
(98, 'ITR', 10, 'Administracion de empresas maritimas'),
(99, 'ITR', 10, 'Politicas de autotransporte maritimo'),
(100, 'ITR', 10, 'Modelos de impacto ambiental del autotransporte maritimo'),
(101, 'ITR', 10, 'Taller intermodal del autotransporte maritimo'),
(102, 'ITR', 10, 'Sistemas inteligentes del autotransporte maritimo'),
(103, 'ITR', 2, 'Calculo'),
(104, 'ITR', 2, 'Geometria analitica'),
(105, 'ITR', 2, 'Mecanica'),
(106, 'ITR', 2, 'Termodinamica'),
(107, 'ITR', 2, 'Probabilidad y estadistica'),
(108, 'ITR', 2, 'Ingles C1'),
(109, 'ITR', 3, 'Optimizacion'),
(110, 'ITR', 3, 'Geometria descriptiva'),
(111, 'ITR', 3, 'Topografia'),
(112, 'ITR', 3, 'Enfoque de sistemas para el transporte'),
(113, 'ITR', 3, 'Tecnologia vehicular del autotransporte I'),
(114, 'ITR', 3, 'Ingles C2'),
(115, 'ITR', 4, 'Ingenieria de transito I'),
(116, 'ITR', 4, 'Metodologia de la investigacion'),
(117, 'ITR', 4, 'Hombre y sociedad'),
(118, 'ITR', 4, 'Tecnologia vehicular del autotransporte II'),
(119, 'ITR', 4, 'Mantenimiento vehicular'),
(120, 'ITR', 4, 'Sistemas de informacion geografica'),
(121, 'ITR', 5, 'Ingenieria de transito II'),
(122, 'ITR', 5, 'Instalaciones del autotransporte'),
(123, 'ITR', 5, 'Dise�o geometrico de infraestructura terrestre'),
(124, 'ITR', 5, 'Sistemas de informacion para el transporte'),
(125, 'ITR', 5, 'Economia del transporte'),
(126, 'ITR', 5, 'Hombre y estado'),
(127, 'ITR', 6, 'Seguridad en el autotransporte'),
(128, 'ITR', 6, 'Estudios de demanda del autotransporte de pasajeros'),
(129, 'ITR', 6, 'Legislacion, politicas y organismos gubernamentales del autotransporte de pasajeros'),
(130, 'ITR', 6, 'Sistemas de transporte masivo'),
(131, 'ITR', 6, 'Administracion y operacion de empresas del autotransporte de pasajeros'),
(132, 'ITR', 6, 'Transportes especiales'),
(133, 'ITR', 7, 'Logistica I'),
(134, 'ITR', 7, 'Evaluacion de proyectos del autotransporte de pasajeros'),
(135, 'ITR', 7, 'Estudios de demanda del autotransporte de carga'),
(136, 'ITR', 7, 'Impacto ambiental del autotransporte'),
(137, 'ITR', 7, 'Administracion y operacion de empresas del autotransporte de carga'),
(138, 'ITR', 7, 'Legislacion, politicas y organismos gubernamentales del autotransporte de carga'),
(139, 'ITR', 8, 'Logistica II '),
(140, 'ITR', 8, 'Transporte intermodal'),
(141, 'ITR', 8, 'Evaluacion de proyectos del autotransporte de carga'),
(142, 'ITR', 8, 'Sistemas inteligentes del autotransporte'),
(143, 'ITR', 8, 'Transporte urbano e interurbano'),
(144, 'ITR', 8, 'Logistica internacional'),
(145, 'ITR', 9, 'Logistica del autotransporte ferroviario'),
(146, 'ITR', 9, 'Modelos de operacion del autotransporte ferroviario'),
(147, 'ITR', 9, 'Infraestructura del autotransporte ferroviario'),
(148, 'ITR', 9, 'Instalaciones del autotransporte ferroviario'),
(149, 'ITR', 9, 'Tecnologia del autotransporte ferroviario'),
(150, 'ITR', 9, 'Seguridad del autotransporte ferroviario'),
(151, 'ITR', 9, 'Evaluacion de proyectos del autotransporte ferroviario'),
(152, 'ITR', 9, 'Logistica del autotransporte aereo'),
(153, 'ITR', 9, 'Modelos de operacion del autotransporte aereo'),
(154, 'ITR', 9, 'Infraestructura del autotransporte aereo'),
(155, 'ITR', 9, 'Instalaciones del autotransporte aereo'),
(156, 'ITR', 9, 'Tecnologia del autotransporte aereo'),
(157, 'ITR', 9, 'Seguridad del autotransporte aereo'),
(158, 'ITR', 9, 'Evaluacion de proyectos del autotransporte aereo'),
(159, 'ITR', 9, 'Logistica del autotransporte maritimo'),
(160, 'ITR', 9, 'Modelos de operacion del autotransporte maritimo'),
(161, 'ITR', 9, 'Infraestructura del autotransporte maritimo'),
(162, 'ITR', 9, 'Instalaciones del autotransporte maritimo'),
(163, 'ITR', 9, 'Tecnologia del autotransporte maritimo'),
(164, 'ITR', 9, 'Seguridad del autotransporte maritimo'),
(165, 'ITR', 9, 'Evaluacion de proyectos del autotransporte maritimo'),
(166, 'LCI', 1, 'Derecho internacional privado'),
(167, 'LCI', 1, 'Contabilidad basica'),
(168, 'LCI', 1, 'Estructura de la micro, peque�a y mediana empresa'),
(169, 'LCI', 1, 'Administracion'),
(170, 'LCI', 1, 'Microeconomia'),
(171, 'LCI', 1, 'Teoria del comercio'),
(172, 'LCI', 1, 'internacional I'),
(173, 'LCI', 10, 'Seminario de titulacion'),
(174, 'LCI', 10, 'Investigacion de mercados internacionales'),
(175, 'LCI', 10, 'Formulacion y evaluacion de proyectos de exportacion'),
(176, 'LCI', 10, 'Practicas profesionales'),
(177, 'LCI', 10, 'Promocion y publicidad internacional'),
(178, 'LCI', 10, 'Estrategias de comunicacion y negociacion internacional'),
(179, 'LCI', 2, 'Derecho internacional publico'),
(180, 'LCI', 2, 'Administracion de mercadotecnia'),
(181, 'LCI', 2, 'Estructura economica y comercial de Mexico'),
(182, 'LCI', 2, 'Macroeconomia'),
(183, 'LCI', 2, 'Teoria del comercio internacional II'),
(184, 'LCI', 2, 'Taller de lectura y redaccion'),
(185, 'LCI', 2, 'Valores socioculturales'),
(186, 'LCI', 3, 'Legislacion del comercio exterior'),
(187, 'LCI', 3, 'Taller de clasificacion arancelaria'),
(188, 'LCI', 3, 'Administracion internacional I'),
(189, 'LCI', 3, 'Estructura de las organizaciones internacionales'),
(190, 'LCI', 3, 'Matematicas aplicadas al comercio internacional I'),
(191, 'LCI', 3, 'Taller de creditos y cobranzas'),
(192, 'LCI', 3, 'Ingles C1'),
(193, 'LCI', 4, 'Taller de incoterms'),
(194, 'LCI', 4, 'Administracion Internacional II'),
(195, 'LCI', 4, 'Sistema de administracion aduanal'),
(196, 'LCI', 4, 'Logistica comercial'),
(197, 'LCI', 4, 'Matematicas aplicadas al comercio internacional II'),
(198, 'LCI', 4, 'Estadistica I'),
(199, 'LCI', 4, 'Ingles C2'),
(200, 'LCI', 5, 'Auditoria y tratamientos fiscales'),
(201, 'LCI', 5, 'Matematicas financieras'),
(202, 'LCI', 5, 'Desarrollo de emprendedores Bloques y regiones del comercio mundial'),
(203, 'LCI', 5, 'Estadistica II'),
(204, 'LCI', 5, 'Ingles D1'),
(205, 'LCI', 5, 'Simulador de negocios internacionales'),
(206, 'LCI', 5, 'Etica en los negocios'),
(207, 'LCI', 5, 'Taller de desarrollo humano y creatividad'),
(208, 'LCI', 6, 'Contabilidad administrativa y comercial'),
(209, 'LCI', 6, 'Marketing internacional I'),
(210, 'LCI', 6, 'Tecnicas de promocion internacional'),
(211, 'LCI', 6, 'Acuerdos, tratados y zonas comerciales'),
(212, 'LCI', 6, 'Investigacion de operaciones'),
(213, 'LCI', 6, 'Ingles D2'),
(214, 'LCI', 7, 'Taller de practicas contractuales'),
(215, 'LCI', 7, 'Modos de transporte internacional'),
(216, 'LCI', 7, 'Marketing internacional II'),
(217, 'LCI', 7, 'Seguros internacionales'),
(218, 'LCI', 7, 'Psicologia organizacional'),
(219, 'LCI', 7, 'Programa de financiamiento al comercio exterior'),
(220, 'LCI', 7, 'Taller de planeacion estrategica'),
(221, 'LCI', 7, 'Derecho aduanero mexicano I'),
(222, 'LCI', 8, 'Legislacion Internacional del medio ambiente'),
(223, 'LCI', 8, 'Alianzas estrategicas en el mercado internacional'),
(224, 'LCI', 8, 'Politica de precios'),
(225, 'LCI', 8, 'Instrumentos bursatiles'),
(226, 'LCI', 8, 'Metodologia de la investigacion documental'),
(227, 'LCI', 8, 'Comercio electronico'),
(228, 'LCI', 8, 'Administracion en el desarrollo de productos para mercados globales'),
(229, 'LCI', 8, 'Derecho aduanero mexicano II'),
(230, 'LCI', 9, 'Finanzas internacionales'),
(231, 'LCI', 9, 'Economia financiera y del sector publico'),
(232, 'LCI', 9, 'Tecnicas de negociacion comercial'),
(233, 'LCI', 9, 'Taller de metodologia de la investigacion de campo'),
(234, 'LCI', 9, 'Sistemas de informacion'),
(235, 'LCI', 9, 'Envase y embalaje'),
(236, 'LCI', 9, 'Marco juridico mexicano del comercio'),
(237, 'LES', 1, 'Politicas y programas para la atencion a la salud comunitaria'),
(238, 'LES', 1, 'Marco normativo para el sector salud'),
(239, 'LES', 1, 'Poblacion y medio ambiente'),
(240, 'LES', 1, 'Marginacion, pobreza y estilos de vida'),
(241, 'LES', 1, 'Antropologia y salud comunitaria'),
(242, 'LES', 1, 'Cartografia digitalizada'),
(243, 'LES', 1, 'Configuracion del mundo actual'),
(244, 'LES', 10, 'Practica integral comunitaria III'),
(245, 'LES', 10, 'Practica integral en instituciones '),
(246, 'LES', 2, 'Factores prenatales y promocion de la salud'),
(247, 'LES', 2, 'Nutricion, consumo y riesgos para la salud'),
(248, 'LES', 2, 'Sistemas de informacion para alerta temprana en salud'),
(249, 'LES', 2, 'Medio ambiente y promocion de la salud'),
(250, 'LES', 2, 'Computacion 1'),
(251, 'LES', 2, 'Ingles C1'),
(252, 'LES', 3, 'Prevencion y promocion de la salud en recien nacidos'),
(253, 'LES', 3, 'Genetica y salud'),
(254, 'LES', 3, 'Sociodemografia y salud I'),
(255, 'LES', 3, 'Estrategias de aprendizaje para grupos y comunidades'),
(256, 'LES', 3, 'Computacion 2'),
(257, 'LES', 3, 'Ingles C2'),
(258, 'LES', 4, 'Prevencion y promocion de la salud en la infancia'),
(259, 'LES', 4, 'Sociodemografia y salud II'),
(260, 'LES', 4, 'Comunicacion para la salud I'),
(261, 'LES', 4, 'Didactica y pedagogia para la salud'),
(262, 'LES', 4, 'Sociologia de la salud'),
(263, 'LES', 4, 'Redes sociales y promocion de la salud'),
(264, 'LES', 4, 'Desarrollo comunitario y redes sociales'),
(265, 'LES', 4, 'Globalizacion y salud'),
(266, 'LES', 5, 'Promocion de la salud adolescente y juvenil I'),
(267, 'LES', 5, 'Familia y salud comunitaria'),
(268, 'LES', 5, 'Comunicacion para la salud II'),
(269, 'LES', 5, 'Educacion y salud I'),
(270, 'LES', 5, 'Calidad de vida y salud'),
(271, 'LES', 5, 'Dise�o y gestion de proyectos'),
(272, 'LES', 6, 'Promocion de la salud adolescente y juvenil II'),
(273, 'LES', 6, 'Estilos de vida y riesgos en la poblacion adulta'),
(274, 'LES', 6, 'Sistemas de informacion en salud I'),
(275, 'LES', 6, 'Perspectiva de genero y salud'),
(276, 'LES', 6, 'Educacion y salud II'),
(277, 'LES', 6, 'Multiculturalismo y salud'),
(278, 'LES', 7, 'Bioetica y promocion de la salud I'),
(279, 'LES', 7, 'Sociodemografia, tercera edad y salud'),
(280, 'LES', 7, 'Sistemas de informacion en salud II'),
(281, 'LES', 7, 'Medios de comunicacion y salud'),
(282, 'LES', 7, 'Migracion, salud y enfermedades'),
(283, 'LES', 7, 'Estratificacion, desigualdad y movilidad social'),
(284, 'LES', 8, 'Bioetica y promocion de la salud II'),
(285, 'LES', 8, 'Practica integral comunitaria I'),
(286, 'LES', 8, 'Seminario de titulacion I'),
(287, 'LES', 8, 'Gestion para la salud comunitaria I'),
(288, 'LES', 8, 'Derechos humanos y salud'),
(289, 'LES', 8, 'Comunicacion regional'),
(290, 'LES', 9, 'Practica integral comunitaria II'),
(291, 'LES', 9, 'Seminario de titulacion II'),
(292, 'LES', 9, 'Gestion para salud comunitaria II'),
(293, 'LES', 9, 'Mercadotecnia social'),
(294, 'LES', 9, 'Educacion y capacitacion'),
(295, 'LSD', 1, 'Introduccion al estudio del Derecho'),
(296, 'LSD', 1, 'Teoria del riesgo e inseguridad social'),
(297, 'LSD', 1, 'Metodos cualitativos de investigacion'),
(298, 'LSD', 1, 'Probabilidad y estadistica'),
(299, 'LSD', 1, 'Sociologia e inseguridad'),
(300, 'LSD', 1, 'Historia de las politicas en seguridad en Mexico'),
(301, 'LSD', 10, 'Practica profesional'),
(302, 'LSD', 2, 'Comunicacion profesiona'),
(303, 'LSD', 2, 'Entrevista en Seguridad'),
(304, 'LSD', 2, 'Derecho constitucional'),
(305, 'LSD', 2, 'Cultura, violencia y delincuencia en Mexico'),
(306, 'LSD', 2, 'Criminologia'),
(307, 'LSD', 2, 'Prevencion del delito'),
(308, 'LSD', 2, 'Manejo de equipo de computo, redes e internet'),
(309, 'LSD', 3, 'Casuistica de los derechos humanos'),
(310, 'LSD', 3, 'Ingles C1'),
(311, 'LSD', 3, 'Analisis economico del sistema de justicia penal'),
(312, 'LSD', 3, 'Derecho pena'),
(313, 'LSD', 3, 'Teorias de la comunicacion y Seguridad Ciudadana'),
(314, 'LSD', 3, 'Estadistica no parametrica'),
(315, 'LSD', 3, 'Desarrollo de politicas en Seguridad'),
(316, 'LSD', 4, 'Deontologia en la Seguridad Ciudadana'),
(317, 'LSD', 4, 'Ingles C2'),
(318, 'LSD', 4, 'Evaluacion de programas sociales'),
(319, 'LSD', 4, 'Modeos lineales'),
(320, 'LSD', 4, 'Modelos de gestion y gerencia en Seguridad Ciudadana'),
(321, 'LSD', 4, 'Derecho procesal penal'),
(322, 'LSD', 5, 'Dilemas y responsabilidad profesional'),
(323, 'LSD', 5, 'Globalizacion, geopolitica y Seguridad Ciudadana'),
(324, 'LSD', 5, 'Sistemas de informacion geografica'),
(325, 'LSD', 5, 'Planeacion prospectiva'),
(326, 'LSD', 5, 'Marco normativo en Seguridad Ciudadana'),
(327, 'LSD', 5, 'Psicologia social'),
(328, 'LSD', 5, 'Antropologia social'),
(329, 'LSD', 5, 'Dise�o y evaluacion de proyectos'),
(330, 'LSD', 6, 'Bases de medicina forense'),
(331, 'LSD', 6, 'Sociologia criminologica'),
(332, 'LSD', 6, 'Desarrollo urbano y demografia para la Seguridad'),
(333, 'LSD', 6, 'Policia'),
(334, 'LSD', 6, 'Modelos de seguridad'),
(335, 'LSD', 6, 'Marco normativo en administracion de justicia'),
(336, 'LSD', 6, 'Grupos vulnerables'),
(337, 'LSD', 7, 'Formas alternativas de solucion de conflictos'),
(338, 'LSD', 7, 'Psicologia criminologica'),
(339, 'LSD', 7, 'Reingenieria de procesos'),
(340, 'LSD', 7, 'Politicas comparadas en seguridad publica y justicia penal'),
(341, 'LSD', 7, 'Politica criminologica'),
(342, 'LSD', 7, 'Programas en prevencion del delito'),
(343, 'LSD', 7, 'Inteligencia criminologica'),
(344, 'LSD', 7, 'Administracion publica y Seguridad Ciudadana'),
(345, 'LSD', 8, 'Criminalistica de campo'),
(346, 'LSD', 8, 'Victimologia'),
(347, 'LSD', 8, 'Analisis delictivo'),
(348, 'LSD', 8, 'Penologia y arbitrio judicial'),
(349, 'LSD', 8, 'Criminalidad en Mexico'),
(350, 'LSD', 8, 'Modelos operativos de intervencion'),
(351, 'LSD', 8, 'Delincuencia organizada'),
(352, 'LSD', 8, 'Metodos de investigacion ministerial 1'),
(353, 'LSD', 8, 'Contraloria social'),
(354, 'LSD', 8, 'Seguridad Ciudadana: teoria y reforma del Estado'),
(355, 'LSD', 9, 'Criminalistica de laboratorio'),
(356, 'LSD', 9, 'Sistema acusatorio'),
(357, 'LSD', 9, 'Formas especificas de violencia y delincuencia en Mexico'),
(358, 'LSD', 9, 'Informpatica en seguridad publica y justicia penal'),
(359, 'LSD', 9, 'Diagnostico y prediccion de la violencia y delincuencia'),
(360, 'LSD', 9, 'Marco normativo en prevencion del delito'),
(361, 'LSD', 9, 'Metodos de investigacion ministerial 2'),
(362, 'LSD', 9, 'Marco normativo en procuracion de justicia'),
(363, 'LSD', 9, 'Problemas contemporaneos en seguridad'),
(364, 'LSD', 9, 'Participacion social en Seguridad Ciudadana');

DROP TABLE IF EXISTS `Preguntas`;
CREATE TABLE IF NOT EXISTS `Preguntas` (
  `id_Pregunta` int NOT NULL,
  `id_Type` int NOT NULL,
  `Pregunta` varchar(200) NOT NULL,
  PRIMARY KEY (`id_Pregunta`),
  KEY `id_Type` (`id_Type`)
);

INSERT INTO `Preguntas` VALUES
(1, 1, 'El profesor evidencia que ha preparado las clases con anticipación'),
(2, 1, 'El profesor demuestra dominio sobre el tema en las explicaciones'),
(3, 1, 'El profesor emplea variedad de ayudas audiovisuales (multimedia, diapositivas, videos, etc.)'),
(4, 1, 'El profesor aplica técnicas y estrategias de evaluación'),
(5, 1, 'El profesor se interesa por los y las estudiantes que demuestran problemas en aprender los temas de estudio'),
(6, 1, 'El profesor demuestra que conoce la clase'),
(7, 1, 'El profesor explica temas con ejemplos de la actualidad'),
(8, 1, 'El profesor utiliza variedad de recursos de enseñanza (demostraciones, lecturas, trabajo en grupo, etc.)'),
(9, 1, 'El o los procedimiento(s) de evaluación permite al alumno reflejar sus conocimientos'),
(10, 1, 'El profesor da respuestas claras a las dudas de los estudiantes'),
(11, 1, 'Los objetivos del curso se definen anticipadamente'),
(12, 1, 'El profesor muestra dominio de los temas tratados'),
(13, 1, 'El profesor crea un ambiente propicio para motivar la participación de los alumnos'),
(14, 1, 'El profesor tiene una forma de enseñar que facilita la comprensión de la materia'),
(15, 1, 'El profesor elabora los exámenes para sintetizar efectivamente la materia del curso'),
(16, 1, 'El profesor trata de acercarse y conversar con los estudiantes antes y después de clase'),
(17, 1, 'El profesor resume y enfatiza los aspectos claves de cada lección'),
(18, 1, 'El profesor integra conocimientos teóricos con los prácticos'),
(19, 1, 'El profesor tiene su forma o técnica de enseñar que facilita la comprensión de la materia'),
(20, 1, 'El profesor es imparcial a la hora de evaluar y calificar (exámenes, tareas, asignaciones, otros)'),
(21, 1, 'El profesor demuestra creatividad en las actividades de la clase'),
(22, 1, 'El profesor demuestra seguridad y confianza en lo que explica'),
(23, 1, 'El profesor realiza actividades prácticas, demostrativas y vivenciales para que los alumnos conozcan donde pueden aplicar los conocimientos'),
(24, 1, 'El profesor genera actividades en grupo que conlleven a objetivos comunes'),
(25, 1, 'El profesor se mantiene activo y dinámico cuando dirige este curso'),
(26, 1, 'El profesor planifica las actividades académicas'),
(27, 1, 'El profesor transmite sus conocimientos con entusiasmo por su asignatura'),
(28, 1, 'El profesor los recursos didácticos son acordes con los temas'),
(29, 1, 'El profesor genera retroalimentación en los exámenes, calificaciones y materiales que le ayudan a comprender el contenido de la clase'),
(30, 1, 'El profesor expresa asertivamente, las propias ideas y escucha las ajenas'),
(31, 2, 'Asistí a todas las clases de la semana'),
(32, 2, 'Estoy satisfecho con los aprendizajes obtenidos después de cada clase'),
(33, 2, 'Vivo un ambiente de respeto en el salón de clases'),
(34, 2, 'Asisto puntualmente a las clases'),
(35, 2, 'Atiendo las explicaciones que da el profesor'),
(36, 2, 'El profesor resolvió todas mis dudas'),
(37, 2, 'Considero adecuado que las mujeres estudien ingeniería'),
(38, 2, 'Realizo las tareas y trabajos que se plantean en clase y aquellas/os extraclase'),
(39, 2, 'Las opiniones y soluciones de mis compañeros (hombres) son una aportación importante para la clase'),
(40, 2, 'Las opiniones y soluciones de mis compañeras (mujeres) son una aportación importante para la clase'),
(41, 3, 'Recomendarías a otras personas estudiar Ingeniería en Sistemas Inteligentes en la UAEMEX'),
(42, 3, 'Te sientes identificado con la carrera y su plan de estudios');

DROP TABLE IF EXISTS `Pregunta_type`;
CREATE TABLE IF NOT EXISTS `Pregunta_type` (
  `id_Type` int NOT NULL,
  `nm_Type` varchar(50) NOT NULL,
  PRIMARY KEY (`id_Type`)
);

INSERT INTO `Pregunta_type` VALUES
(1, 'Desempeño Docente'),
(2, 'Desempeño Estudiantil'),
(3, 'Identidad Institucional');

DROP TABLE IF EXISTS `RespDsmpDcnte`;
CREATE TABLE IF NOT EXISTS `RespDsmpDcnte` (
  `id_RespDcnte` int NOT NULL AUTO_INCREMENT,
  `id_Alumno` int NOT NULL,
  `id_Materia` int NOT NULL,
  `respuesta_1` int NOT NULL,
  `respuesta_2` int NOT NULL,
  `respuesta_3` int NOT NULL,
  `respuesta_4` int NOT NULL,
  `respuesta_5` int NOT NULL,
  `respuesta_6` int NOT NULL,
  `respuesta_7` int NOT NULL,
  `respuesta_8` int NOT NULL,
  `respuesta_9` int NOT NULL,
  `respuesta_10` int NOT NULL,
  `respuesta_11` int NOT NULL,
  `respuesta_12` int NOT NULL,
  `respuesta_13` int NOT NULL,
  `respuesta_14` int NOT NULL,
  `respuesta_15` int NOT NULL,
  `respuesta_16` int NOT NULL,
  `respuesta_17` int NOT NULL,
  `respuesta_18` int NOT NULL,
  `respuesta_19` int NOT NULL,
  `respuesta_20` int NOT NULL,
  `respuesta_21` int NOT NULL,
  `respuesta_22` int NOT NULL,
  `respuesta_23` int NOT NULL,
  `respuesta_24` int NOT NULL,
  `respuesta_25` int NOT NULL,
  `respuesta_26` int NOT NULL,
  `respuesta_27` int NOT NULL,
  `respuesta_28` int NOT NULL,
  `respuesta_29` int NOT NULL,
  `respuesta_30` int NOT NULL,
  PRIMARY KEY (`id_RespDcnte`),
  KEY `id_Alumno` (`id_Alumno`),
  KEY `id_Materia` (`id_Materia`) USING BTREE
);

DROP TABLE IF EXISTS `RespDsmpEstdtl`;
CREATE TABLE IF NOT EXISTS `RespDsmpEstdtl` (
  `id_RespDsmpEstdtl` int NOT NULL AUTO_INCREMENT,
  `id_Alumno` int NOT NULL,
  `id_Materia` int NOT NULL,
  `respuesta_1` int NOT NULL,
  `respuesta_2` int NOT NULL,
  `respuesta_3` int NOT NULL,
  `respuesta_4` int NOT NULL,
  `respuesta_5` int NOT NULL,
  `respuesta_6` int NOT NULL,
  `respuesta_7` int NOT NULL,
  `respuesta_8` int NOT NULL,
  `respuesta_9` int NOT NULL,
  `respuesta_10` int NOT NULL,
  PRIMARY KEY (`id_RespDsmpEstdtl`),
  KEY `id_Alumno` (`id_Alumno`),
  KEY `id_Materia` (`id_Materia`) USING BTREE
);

DROP TABLE IF EXISTS `RespIdntInst`;
CREATE TABLE IF NOT EXISTS `RespIdntInst` (
  `id_RespIndtInst` int NOT NULL AUTO_INCREMENT,
  `id_Alumno` int NOT NULL,
  `respuesta_1` int NOT NULL,
  `respuesta_2` int NOT NULL,
  PRIMARY KEY (`id_RespIndtInst`),
  KEY `id_Alumno` (`id_Alumno`)
);

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `expires` int UNSIGNED NOT NULL,
  `data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
);

INSERT INTO `sessions` VALUES
('FOTKXaiC4x6uDf-lL_Jj49t9PcIVawWV', 1669531258, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"flash\":{}}'),
('XCuO3-z_3Eg4mwDitKVPic0jZ-JlAr1j', 1669530643, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"flash\":{\"success\":[\"Favor de resporder el siguiente cuestionario\"]},\"passport\":{\"user\":0}}'),
('e6nLncC4gAMMAOVE54D-kz5Hk5-zcWdr', 1669531127, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"flash\":{\"success\":[\"Favor de resporder el siguiente cuestionario\"]},\"passport\":{\"user\":0}}'),
('eiPqwRaIxhpM_qdRU5fBMQkJ14SmRel4', 1669528103, '{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"},\"flash\":{}}');


ALTER TABLE `Alumnos`
  ADD CONSTRAINT `Alumnos_ibfk_1` FOREIGN KEY (`id_Carrera`) REFERENCES `Carrera` (`id_Carrera`);

ALTER TABLE `Materias`
  ADD CONSTRAINT `Materias_ibfk_1` FOREIGN KEY (`id_Carrera`) REFERENCES `Carrera` (`id_Carrera`);

ALTER TABLE `Preguntas`
  ADD CONSTRAINT `Preguntas_ibfk_1` FOREIGN KEY (`id_Type`) REFERENCES `Pregunta_type` (`id_Type`);

ALTER TABLE `RespDsmpDcnte`
  ADD CONSTRAINT `RespDsmpDcnte_ibfk_1` FOREIGN KEY (`id_Alumno`) REFERENCES `Alumnos` (`Cuenta`),
  ADD CONSTRAINT `RespDsmpDcnte_ibfk_2` FOREIGN KEY (`id_Materia`) REFERENCES `Materias` (`id_Materia`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `RespDsmpEstdtl`
  ADD CONSTRAINT `RespDsmpEstdtl_ibfk_1` FOREIGN KEY (`id_Alumno`) REFERENCES `Alumnos` (`Cuenta`),
  ADD CONSTRAINT `RespDsmpEstdtl_ibfk_2` FOREIGN KEY (`id_Materia`) REFERENCES `Materias` (`id_Materia`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `RespIdntInst`
  ADD CONSTRAINT `RespIdntInst_ibfk_1` FOREIGN KEY (`id_Alumno`) REFERENCES `Alumnos` (`Cuenta`);
COMMIT;
